import { createConnection } from 'mysql2/promise';

const conn = await createConnection(process.env.DATABASE_URL);

// New partners from BiorceStrategicMappingDiagram5.pdf
// Organized by the 10 categories in the document
// Existing: Novartis(6), Pfizer(7), J&J(9), Eli Lilly(3), Veeva(13), FDA(2), Norrsken(20)
// We'll UPDATE those with new contact/strategy info and INSERT the rest

const newPartners = [
  // === 01 PHARMA & BIOTECH ===
  {
    name: 'Novo Nordisk',
    type: 'pharma',
    tier: 'P0',
    stage: 'outreach',
    region: 'Europe',
    description: 'LIGHTHOUSE PHARMA - Partnership 02 in the five-partnership sequence. The first named logo. Social proof compresses every enterprise and partner conversation that follows.',
    mutualValue: 'Paid retrospective backtest on their own protocols. Capped, therapy-area-exclusive design-partner slot for logo rights.',
    nextAction: 'Contact Anne C. Fleischer (AVP Business Development, West Europe) to open design-partner conversation',
    notes: 'Contact: Anne C. Fleischer, AVP Business Development, West Europe. Relationship label: DIRECT and LIVE. First move: paid retrospective backtest on their own protocols, capped therapy-area-exclusive slot for logo rights. Strategic sequence: Partnership 02 - Lighthouse Pharma. GSK also reachable via podcast thread.',
    estimatedArrImpact: 500000,
  },
  {
    name: 'GSK',
    type: 'pharma',
    tier: 'P0',
    stage: 'researching',
    region: 'Europe',
    description: 'Reachable via podcast thread. Part of the Lighthouse Pharma track alongside Novo Nordisk.',
    mutualValue: 'Design-partner slot; named logo for social proof.',
    nextAction: 'Warm re-entry via podcast thread contact',
    notes: 'Contact: Named contacts across brand, medical and commercial. Relationship label: WARM THREAD, not mine to claim. Reachable via podcast thread. Part of J&J / Pfizer / MSD / Sanofi / Esteve / GSK bench for warm introductions.',
    estimatedArrImpact: 400000,
  },
  {
    name: 'Bayer',
    type: 'pharma',
    tier: 'P1',
    stage: 'identified',
    region: 'Europe',
    description: 'External Partnerships & Innovation remit fits a scoped pilot.',
    mutualValue: 'Scoped pilot on protocol design or feasibility module.',
    nextAction: 'Reach out to Ishita Kumar (External Partnerships & Innovation)',
    notes: 'Contact: Ishita Kumar, External Partnerships & Innovation. Relationship label: direct. A remit that fits a scoped pilot.',
    estimatedArrImpact: 200000,
  },
  {
    name: 'MSD (Merck)',
    type: 'pharma',
    tier: 'P1',
    stage: 'identified',
    region: 'Global',
    description: 'Named contacts across brand, medical and commercial. Part of the warm introduction bench.',
    mutualValue: 'Protocol design and regulatory submission acceleration.',
    nextAction: 'Warm introduction via existing bench contacts',
    notes: 'Relationship label: named contacts across brand, medical and commercial. Part of J&J / Pfizer / MSD / Sanofi / Esteve / GSK bench.',
    estimatedArrImpact: 300000,
  },
  {
    name: 'Sanofi',
    type: 'pharma',
    tier: 'P1',
    stage: 'identified',
    region: 'Europe',
    description: 'Named contacts across brand, medical and commercial. Part of the warm introduction bench.',
    mutualValue: 'Protocol design, regulatory submission, and feasibility modules.',
    nextAction: 'Warm introduction via existing bench contacts',
    notes: 'Relationship label: named contacts across brand, medical and commercial. Part of J&J / Pfizer / MSD / Sanofi / Esteve / GSK bench.',
    estimatedArrImpact: 300000,
  },
  {
    name: 'Esteve',
    type: 'pharma',
    tier: 'P2',
    stage: 'identified',
    region: 'Spain',
    description: 'Spanish pharma. Named contacts across brand, medical and commercial.',
    mutualValue: 'Protocol design and local regulatory expertise.',
    nextAction: 'Warm introduction via existing bench contacts',
    notes: 'Relationship label: named contacts. Part of J&J / Pfizer / MSD / Sanofi / Esteve / GSK bench. Local Spanish pharma relationship.',
    estimatedArrImpact: 100000,
  },

  // === 02 AI LABS & FRONTIER MODELS ===
  {
    name: 'Google (Cloud + CTO Office)',
    type: 'tech',
    tier: 'P0',
    stage: 'active',
    region: 'Global',
    description: 'Routes to deepen the existing relationship. NVIDIA and Google to be converted into public case studies by Day 30.',
    mutualValue: 'Joint healthcare case study; deepen Cloud and AI partnership; EMEA ecosystem positioning.',
    nextAction: 'Convert existing relationship into public case study by Day 30. Contact Pablo Rodriguez (Director, CTO Office)',
    notes: 'Contacts: Pablo Rodriguez, PhD, Director, CTO Office; Hanne Tuomisto-Inch, Director, EMEA Ecosystem Partnerships; plus Cloud leadership. Relationship label: DIRECT. Day 1-30 priority: convert into public case study.',
    estimatedArrImpact: 0,
  },
  {
    name: 'OpenAI',
    type: 'tech',
    tier: 'P1',
    stage: 'identified',
    region: 'Global',
    description: 'First-degree into the commercial side via David Dugan.',
    mutualValue: 'Model partnership; potential integration into Aika platform.',
    nextAction: 'Reach out to David Dugan (VP, Head of Global Ads Solutions) for commercial introduction',
    notes: 'Contact: David Dugan, VP, Head of Global Ads Solutions. Relationship label: first-degree into commercial side.',
    estimatedArrImpact: 0,
  },
  {
    name: 'Anthropic',
    type: 'tech',
    tier: 'P1',
    stage: 'identified',
    region: 'Global',
    description: 'A model-partnership conversation via Mike Boufford.',
    mutualValue: 'Model partnership; Claude integration for explainable AI in clinical protocols.',
    nextAction: 'Contact Mike Boufford (Member of Technical Staff, Manager) for model-partnership conversation',
    notes: 'Contact: Mike Boufford, Member of Technical Staff, Manager. Relationship label: direct. A model-partnership conversation.',
    estimatedArrImpact: 0,
  },

  // === 03 AI INFRASTRUCTURE & COMPUTE (IN HAND) ===
  {
    name: 'NVIDIA (Inception Program)',
    type: 'tech',
    tier: 'P0',
    stage: 'active',
    region: 'Global',
    description: 'ECOSYSTEM CREDIBILITY - Partnership 01 IN HAND. Compute and European-AI-champion legitimacy that lowers the cost of every pharma and regulator conversation.',
    mutualValue: 'Joint healthcare case study + AI-Factory compute conversation. Inception membership active.',
    nextAction: 'Structure joint healthcare case study with Tobias Halloran. Convert to public case study by Day 30.',
    notes: 'Contact: Tobias Halloran, Director, Startups EMEAI, plus Inception membership. Relationship label: IN HAND. First move: joint healthcare case study + AI-Factory compute conversation, week one. Strategic sequence: Partnership 01 - Ecosystem Credibility.',
    estimatedArrImpact: 0,
  },
  {
    name: 'BSC - Barcelona Supercomputing Center',
    type: 'tech',
    tier: 'P0',
    stage: 'active',
    region: 'Spain',
    description: 'ECOSYSTEM CREDIBILITY - Partnership 01 IN HAND alongside NVIDIA. AI Factory selection. European-champion legitimacy.',
    mutualValue: 'Compute access; European AI champion positioning; AI Factory selection.',
    nextAction: 'Open BSC compute access and convert to public case study by Day 30.',
    notes: 'Contacts: Santi Trujillo, AI Startups KAM; Monica Mateu, Innovation. Relationship label: IN HAND. Compute, European-champion legitimacy, AI Factory selection.',
    estimatedArrImpact: 0,
  },

  // === 04 INVESTORS & ECOSYSTEM ===
  {
    name: 'Medicxi',
    type: 'investor',
    tier: 'P1',
    stage: 'identified',
    region: 'Europe',
    description: 'Top-tier European biotech VC; a serious pharma-and-science ecosystem door.',
    mutualValue: 'Series B syndicate; pharma ecosystem introductions.',
    nextAction: 'Contact Francesco De Rubertis (Co-founder and Partner)',
    notes: 'Contact: Francesco De Rubertis, Co-founder and Partner. A top-tier European biotech VC; a serious pharma-and-science ecosystem door.',
    estimatedArrImpact: 0,
  },
  {
    name: 'Lakestar',
    type: 'investor',
    tier: 'P1',
    stage: 'identified',
    region: 'Europe',
    description: 'European VC with IR and communications leadership.',
    mutualValue: 'Series B syndicate; ecosystem positioning.',
    nextAction: 'Contact Ninja Struye de Swielande (Partner and Chief Communication Officer / Head of IR)',
    notes: 'Contact: Ninja Struye de Swielande, Partner and Chief Communication Officer / Head of IR.',
    estimatedArrImpact: 0,
  },
  {
    name: 'Founders Factory / Founders Forum',
    type: 'investor',
    tier: 'P1',
    stage: 'identified',
    region: 'Europe',
    description: 'Channel toward Northwestern Medicine via David Hickson. Brent Hoberman reachable directly.',
    mutualValue: 'Channel to Northwestern Medicine; ecosystem convening; seed VC relationship.',
    nextAction: 'Contact Brent Hoberman (Co-founder and Executive Chair) or George Northcott / Henry Lane Fox / David Hickson',
    notes: 'Contacts: Brent Hoberman, Co-founder and Executive Chair; George Northcott, Henry Lane Fox, David Hickson. The channel toward Northwestern Medicine.',
    estimatedArrImpact: 0,
  },
  {
    name: 'First Minute Capital',
    type: 'investor',
    tier: 'P2',
    stage: 'identified',
    region: 'Europe',
    description: 'Seed VC reachable directly via Brent Hoberman.',
    mutualValue: 'Series B syndicate support.',
    nextAction: 'Contact Brent Hoberman (Co-founder)',
    notes: 'Contact: Brent Hoberman, Co-founder. A seed VC reachable directly.',
    estimatedArrImpact: 0,
  },
  {
    name: 'Team8',
    type: 'investor',
    tier: 'P2',
    stage: 'identified',
    region: 'Global',
    description: 'Venture group relationship via Yuval Sachel.',
    mutualValue: 'Series B syndicate; cybersecurity and enterprise tech ecosystem.',
    nextAction: 'Contact Yuval Sachel',
    notes: 'Contact: Yuval Sachel. A relationship at the Team8 venture group.',
    estimatedArrImpact: 0,
  },
  {
    name: 'Intel Capital',
    type: 'investor',
    tier: 'P2',
    stage: 'identified',
    region: 'Global',
    description: 'Corporate-VC relationship via Erica Van.',
    mutualValue: 'Corporate VC for Series B; Intel compute partnership potential.',
    nextAction: 'Contact Erica Van (Partner)',
    notes: 'Contact: Erica Van, Partner. A corporate-VC relationship.',
    estimatedArrImpact: 0,
  },
  {
    name: 'Endeavor / Endeavor Catalyst',
    type: 'investor',
    tier: 'P2',
    stage: 'identified',
    region: 'LatAm',
    description: 'Endeavor Catalyst is a Series A investor. Felipe Ossa, Managing Director, Endeavor Colombia.',
    mutualValue: 'LatAm market access; existing Series A relationship to deepen.',
    nextAction: 'Contact Felipe Ossa (Managing Director, Endeavor Colombia)',
    notes: 'Contact: Felipe Ossa, Managing Director, Endeavor Colombia. Endeavor Catalyst is a Series A investor.',
    estimatedArrImpact: 0,
  },
  {
    name: 'Innova Capital',
    type: 'investor',
    tier: 'P2',
    stage: 'identified',
    region: 'Europe',
    description: 'Growth capital relationship via Veronica Allende Serra.',
    mutualValue: 'Series B syndicate.',
    nextAction: 'Contact Veronica Allende Serra (Founding Partner)',
    notes: 'Contact: Veronica Allende Serra, Founding Partner.',
    estimatedArrImpact: 0,
  },
  {
    name: 'I2BF Global Ventures',
    type: 'investor',
    tier: 'P2',
    stage: 'identified',
    region: 'Global',
    description: 'Deep-tech VC relationship via Denis Kalyshkin.',
    mutualValue: 'Series B syndicate; deep-tech positioning.',
    nextAction: 'Contact Denis Kalyshkin (Principal)',
    notes: 'Contact: Denis Kalyshkin, Principal. A deep-tech VC relationship.',
    estimatedArrImpact: 0,
  },
  {
    name: 'Da Vinci Capital',
    type: 'investor',
    tier: 'P2',
    stage: 'identified',
    region: 'Europe',
    description: 'Growth-capital relationship via Oleg Victor Jelesko.',
    mutualValue: 'Series B growth capital.',
    nextAction: 'Contact Oleg Victor Jelesko (Managing Partner)',
    notes: 'Contact: Oleg Victor Jelesko, Managing Partner. A growth-capital relationship.',
    estimatedArrImpact: 0,
  },
  {
    name: 'Kereon Partners',
    type: 'investor',
    tier: 'P2',
    stage: 'identified',
    region: 'Europe',
    description: 'European VC via Joaquin Sanz Berrioategortua.',
    mutualValue: 'Series B syndicate.',
    nextAction: 'Contact Joaquin Sanz Berrioategortua, PhD (Partner)',
    notes: 'Contact: Joaquin Sanz Berrioategortua, PhD, Partner.',
    estimatedArrImpact: 0,
  },
  {
    name: 'Lluís Pedragosa (VC)',
    type: 'investor',
    tier: 'P2',
    stage: 'identified',
    region: 'Spain',
    description: 'Managing Partner and Co-Founder. European deep-tech VC, for syndicate and ecosystem support.',
    mutualValue: 'Series B syndicate; Barcelona ecosystem.',
    nextAction: 'Direct outreach to Lluis Pedragosa',
    notes: 'Contact: Lluis Pedragosa, Managing Partner and Co-Founder. European deep-tech VC, for syndicate and ecosystem support.',
    estimatedArrImpact: 0,
  },
  {
    name: 'Healthcare.com (Jose Vargas)',
    type: 'investor',
    tier: 'P2',
    stage: 'identified',
    region: 'Global',
    description: 'Healthcare-focused investor and industry relationship.',
    mutualValue: 'Healthcare investor network; industry introductions.',
    nextAction: 'Contact Jose Vargas (VC)',
    notes: 'Contact: Jose Vargas, VC. A healthcare-focused investor and industry relationship.',
    estimatedArrImpact: 0,
  },
  {
    name: 'Mobile World Capital',
    type: 'investor',
    tier: 'P2',
    stage: 'identified',
    region: 'Spain',
    description: 'Barcelona tech-ecosystem convening power via Grace Olea.',
    mutualValue: 'Barcelona ecosystem positioning; MWC network.',
    nextAction: 'Contact Grace Olea (Business Development)',
    notes: 'Contact: Grace Olea, Business Development. Barcelona tech-ecosystem convening power.',
    estimatedArrImpact: 0,
  },

  // === 05 CONSULTANCIES & ADVISORY ===
  {
    name: 'Accenture',
    type: 'consultant',
    tier: 'P1',
    stage: 'identified',
    region: 'Global',
    description: 'Route into pharma transformation programmes via Frans Stokman and Renee Mellow.',
    mutualValue: 'Channel into pharma digital transformation programmes; Song creative leadership.',
    nextAction: 'Contact Frans Stokman (Senior Managing Director) or Renee Mellow (Managing Director)',
    notes: 'Contacts: Frans Stokman, Senior Managing Director; Renee Mellow, Managing Director; plus Song creative leadership. A route into pharma transformation programmes.',
    estimatedArrImpact: 200000,
  },
  {
    name: 'Deloitte',
    type: 'consultant',
    tier: 'P1',
    stage: 'identified',
    region: 'Global',
    description: 'Pharma-advisory channel and introduction network. Monitor Deloitte and Deloitte Digital routes.',
    mutualValue: 'Pharma advisory channel; introduction network into regulated-industry programmes.',
    nextAction: 'Contact Ben Wood, Kadu Pereira, or Dominique Frison (Directors); Fabian Falkenstein (Monitor Deloitte); Ana Costa (Deloitte Digital)',
    notes: 'Contacts: Directors Ben Wood, Kadu Pereira, Dominique Frison; Monitor Deloitte, Fabian Falkenstein; Deloitte Digital, Ana Costa. A pharma-advisory channel and introduction network.',
    estimatedArrImpact: 150000,
  },
  {
    name: 'EY',
    type: 'consultant',
    tier: 'P2',
    stage: 'identified',
    region: 'Global',
    description: 'Advisory channel into regulated-industry programmes via Pablo de Porcioles and Sarah Miles.',
    mutualValue: 'Advisory channel into regulated-industry programmes.',
    nextAction: 'Contact Pablo de Porcioles (Director, Business Consulting) or Sarah Miles (Director, EMEIA Executive Office)',
    notes: 'Contacts: Pablo de Porcioles, Director, Business Consulting; Sarah Miles, Director, EMEIA Executive Office. An advisory channel into regulated-industry programmes.',
    estimatedArrImpact: 100000,
  },
  {
    name: 'BCG',
    type: 'consultant',
    tier: 'P2',
    stage: 'identified',
    region: 'Global',
    description: 'Entry point to deepen into the wider firm via Rachael Jacob (RISE by BCG).',
    mutualValue: 'Pharma strategy advisory channel.',
    nextAction: 'Contact Rachael Jacob (RISE by BCG)',
    notes: 'Contact: Rachael Jacob, RISE by BCG. An entry point to deepen into the wider firm.',
    estimatedArrImpact: 100000,
  },

  // === 06 HOSPITALS & HEALTH SYSTEMS ===
  {
    name: 'Hospital Clinic / IDIBAPS, Barcelona',
    type: 'hospital',
    tier: 'P0',
    stage: 'outreach',
    region: 'Spain',
    description: 'Entry into the Barcelona academic-hospital cluster. Clinical and epidemiology expertise.',
    mutualValue: 'Hospital framework instantiated in EU; real-world outcome data; academic validation.',
    nextAction: 'Contact Alberto Garcia-Basteiro (clinical and epidemiology) for hospital framework conversation',
    notes: 'Contact: Alberto Garcia-Basteiro, clinical and epidemiology. Entry into the Barcelona academic-hospital cluster. Day 31-70 priority: one hospital framework, instantiated twice, one EU and one US.',
    estimatedArrImpact: 150000,
  },
  {
    name: 'The Brain Clinic, Dubai',
    type: 'hospital',
    tier: 'P1',
    stage: 'identified',
    region: 'Middle East',
    description: 'Direct hospital route into the Middle East via Danny Van Otterdyk.',
    mutualValue: 'Middle East market entry; site network expansion.',
    nextAction: 'Contact Danny Van Otterdyk for Middle East hospital route',
    notes: 'Contact: Danny Van Otterdyk. A direct hospital route into the Middle East.',
    estimatedArrImpact: 100000,
  },
  {
    name: 'NHS, UK',
    type: 'hospital',
    tier: 'P1',
    stage: 'identified',
    region: 'UK',
    description: 'NHS relationships to build a site conversation from. Surrey and Borders + RNOH.',
    mutualValue: 'UK site network; NHS validation for European regulatory conversations.',
    nextAction: 'Contact Andy Schiller (Surrey and Borders) or Julian Johnson (RNOH)',
    notes: 'Contacts: Andy Schiller, Surrey and Borders; Julian Johnson, RNOH. NHS relationships to build a site conversation from.',
    estimatedArrImpact: 200000,
  },
  {
    name: 'The London Clinic',
    type: 'hospital',
    tier: 'P2',
    stage: 'identified',
    region: 'UK',
    description: 'Private hospital route in London to reopen.',
    mutualValue: 'UK private hospital site; outcome data loop.',
    nextAction: 'Executive approach to reopen the London Clinic relationship',
    notes: 'A private-hospital route in London to reopen. Executive approach in motion.',
    estimatedArrImpact: 80000,
  },
  {
    name: 'Velocity Clinical Research / Care Access',
    type: 'hospital',
    tier: 'P0',
    stage: 'outreach',
    region: 'US',
    description: 'PROOF OF EXECUTION - Partnership 04. US site network for contracted outcome-data loop. Once predictions can be proven against real execution you sell evidence, not claims.',
    mutualValue: 'Two-study feedback-schema pilot on FHIR/EHR substrate. Contracted outcome-data loop.',
    nextAction: 'Executive outreach with two-study feedback-schema pilot proposal on FHIR/EHR substrate',
    notes: 'Partnership 04 - Proof of Execution. US site networks: Velocity, Care Access. First move: executive outreach with a two-study feedback-schema pilot on a FHIR/EHR substrate. The data compounds once predictions are proven against real execution.',
    estimatedArrImpact: 300000,
  },

  // === 07 EHR & DATA ===
  {
    name: 'Oracle Health / Cerner',
    type: 'tech',
    tier: 'P1',
    stage: 'identified',
    region: 'Global',
    description: 'Real route for the EHR-data conversation via Adriana Landwehrkamp and Florencia Williams.',
    mutualValue: 'EHR data integration; ISV partnership; patient data access for outcome loops.',
    nextAction: 'Contact Adriana Landwehrkamp (Executive Director) or Florencia Williams (ISV Sales)',
    notes: 'Contacts: Adriana Landwehrkamp, Executive Director; Florencia Williams, ISV Sales. A real route for the EHR-data conversation.',
    estimatedArrImpact: 200000,
  },
  {
    name: 'Epic',
    type: 'tech',
    tier: 'P1',
    stage: 'identified',
    region: 'US',
    description: 'Marketplace and partner track for EHR integration.',
    mutualValue: 'Epic Marketplace listing; EHR data integration for US hospital sites.',
    nextAction: 'File Epic Marketplace application and initiate partner track',
    notes: 'Marketplace and partner track. Key for US hospital site EHR data access.',
    estimatedArrImpact: 250000,
  },

  // === 08 CLINICAL SAAS PLATFORMS ===
  {
    name: 'Medidata (Dassault Systemes)',
    type: 'tech',
    tier: 'P1',
    stage: 'researching',
    region: 'Global',
    description: 'Partner-program route. A platform partnership to open. Note: WCT/Medidata strategy drift is an open discrepancy.',
    mutualValue: 'Platform partnership; embedded workflow access; channel into existing Medidata customer base.',
    nextAction: 'Open partner-program route conversation',
    notes: 'Partner-program route. A platform partnership to open. CAUTION: WCT/Medidata April 2026 vs. Biorce Pipeline is an open high-severity discrepancy in the system. Resolve before deepening.',
    estimatedArrImpact: 300000,
  },
  {
    name: 'THREAD (Decentralised Trials)',
    type: 'tech',
    tier: 'P1',
    stage: 'identified',
    region: 'Global',
    description: 'Partner-program route into decentralised-trial tooling.',
    mutualValue: 'DCT integration; embedded in decentralised trial workflows.',
    nextAction: 'Open partner-program route into decentralised-trial tooling',
    notes: 'Partner-program route into decentralised-trial tooling.',
    estimatedArrImpact: 150000,
  },
  {
    name: 'Javara / Access (Site Networks)',
    type: 'hospital',
    tier: 'P1',
    stage: 'outreach',
    region: 'US',
    description: 'Executive approach in motion. The peer-level route to the outcome-data loop.',
    mutualValue: 'US site network access; outcome-data loop for proof of execution.',
    nextAction: 'Executive approach in motion - follow up on peer-level route',
    notes: 'Executive approach in motion. The peer-level route to the outcome-data loop.',
    estimatedArrImpact: 200000,
  },

  // === 09 CROs ===
  {
    name: 'IQVIA',
    type: 'cro',
    tier: 'P1',
    stage: 'researching',
    region: 'Global',
    description: 'Warm thread from podcast. Mid-tier and global CROs sequenced per the main plan.',
    mutualValue: 'CRO channel; embedded in IQVIA customer workflows.',
    nextAction: 'Contact Gilda Longobardi (Sr HR Business Partner) and follow IQVIA thread from podcast',
    notes: 'Contact: Gilda Longobardi, Sr HR Business Partner, plus the IQVIA thread from podcast. Relationship label: WARM THREAD, not mine to claim. Note: Global CRO watchlist - channel conflict unresolved; a mid-tier partner delivers the reference case faster. Held as a scoped pilot.',
    estimatedArrImpact: 250000,
  },

  // === 10 REGULATORS & PUBLIC BODIES ===
  {
    name: 'EMA (European Medicines Agency)',
    type: 'regulator',
    tier: 'P0',
    stage: 'outreach',
    region: 'Europe',
    description: 'EU regulatory relationship. Ana Zanoletty is the single most role-relevant EU regulator route.',
    mutualValue: 'EU regulatory validation; AESIA sandbox note; AEMPS session.',
    nextAction: 'Contact Ana Zanoletty (Head of Clinical Trials Transformation) and file AESIA sandbox note + AEMPS session',
    notes: 'Contact: Ana Zanoletty, Head of Clinical Trials Transformation. The single most role-relevant EU regulator route. Day 31-70: AESIA sandbox note and AEMPS session filed; APAC landscape memo.',
    estimatedArrImpact: 0,
  },
  {
    name: 'AESIA / AEMPS / red.es (Spain)',
    type: 'regulator',
    tier: 'P1',
    stage: 'identified',
    region: 'Spain',
    description: 'Innovation-office and sandbox routes. Spain regulatory relationships.',
    mutualValue: 'Spanish regulatory sandbox; AEMPS session for EU validation.',
    nextAction: 'File AESIA sandbox note and book AEMPS session',
    notes: 'Innovation-office and sandbox routes I know how to open. Day 31-70 priority.',
    estimatedArrImpact: 0,
  },

  // === ACADEMIC VALIDATION (Partnership 05 - Series B Asset) ===
  {
    name: 'Academic Validation Study (Clara-led)',
    type: 'standards_body',
    tier: 'P0',
    stage: 'outreach',
    region: 'Global',
    description: 'INDEPENDENT EVIDENCE - Partnership 05 SERIES B ASSET. Academic validation study co-led by Clara, no veto on results. Third-party validation of headline claims compresses every enterprise sale and the raise itself.',
    mutualValue: 'Pre-registered study agreement that turns self-reported metrics into citable evidence.',
    nextAction: 'Agree pre-registered study protocol with Clara. Identify academic institution co-lead.',
    notes: 'Partnership 05 - Independent Evidence. Co-led by Clara Bernardes, no veto on results. First move: pre-registered study agreement that turns self-reported metrics into citable evidence. This is a Series B asset.',
    estimatedArrImpact: 0,
  },
];

let inserted = 0;
let errors = 0;

for (const p of newPartners) {
  try {
    await conn.execute(
      `INSERT INTO partners (name, type, tier, stage, region, description, mutualValue, nextAction, notes, estimatedArrImpact, createdAt, updatedAt)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW(), NOW())
       ON DUPLICATE KEY UPDATE
         type = VALUES(type),
         tier = VALUES(tier),
         stage = VALUES(stage),
         region = VALUES(region),
         description = VALUES(description),
         mutualValue = VALUES(mutualValue),
         nextAction = VALUES(nextAction),
         notes = VALUES(notes),
         estimatedArrImpact = VALUES(estimatedArrImpact),
         updatedAt = NOW()`,
      [p.name, p.type, p.tier, p.stage, p.region || 'Global', p.description, p.mutualValue, p.nextAction, p.notes, p.estimatedArrImpact || 0]
    );
    inserted++;
    console.log('OK:', p.name);
  } catch (e) {
    errors++;
    console.error('ERR:', p.name, e.message);
  }
}

// Update existing partners with new contact/strategy info from the document
const updates = [
  { name: 'Novartis', notes: 'Contact: Sander Timmer, PhD, Head of AI & Data Science, Global Drug Development. The most role-relevant pharma door in the network. Part of J&J / Pfizer / MSD / Sanofi / Esteve / GSK bench for warm introductions.', tier: 'P0', stage: 'researching' },
  { name: 'Eli Lilly', notes: 'Contact: Lina Polimeni, SVP and CMO, Consumer. A strong senior internal referral route. Also relevant: 30x30 Initiative (30 protocols needed by 2030) - major opportunity.', tier: 'P0', stage: 'outreach' },
  { name: 'Veeva Systems', notes: 'CHANNEL & EMBEDDEDNESS - Partnership 03 TIME-SENSITIVE. Contact: Destry Sulkes, commercial-side AI leadership. A warm internal route into the Development Cloud partner team. Time-sensitive with August GA. First move: file the Veeva Technology Partner application, draft the USDM-native export spec, force partner-or-interoperate inside 30 days. M11-native authoring position is unclaimed and winner-take-most.', tier: 'P0', stage: 'outreach' },
  { name: 'FDA Digital Health Center of Excellence', notes: 'Contacts: Barry W. Miller, Portfolio Management Director; Leora Benson Willner, PhD, Clinical Data Scientist; Tiffany Branch, J.D., Office of the Commissioner. Alongside the live thread on own AI-protocol submission. Day 1-30: warm re-entry and FDA follow-through. Day 31-70: FDA dialogue formalised.', tier: 'P0', stage: 'active' },
];

for (const u of updates) {
  try {
    await conn.execute(
      'UPDATE partners SET notes = ?, tier = ?, stage = ?, updatedAt = NOW() WHERE name = ?',
      [u.notes, u.tier, u.stage, u.name]
    );
    console.log('UPDATED:', u.name);
  } catch (e) {
    console.error('UPDATE ERR:', u.name, e.message);
  }
}

const [countRow] = await conn.execute('SELECT COUNT(*) as total FROM partners');
console.log('\nFINAL TOTAL PARTNERS:', countRow[0].total);
console.log('Inserted/upserted:', inserted, '| Errors:', errors);
await conn.end();
