import mysql from "mysql2/promise";
import dotenv from "dotenv";
dotenv.config();

const conn = await mysql.createConnection(process.env.DATABASE_URL);

// ─── Competitors ──────────────────────────────────────────────────────────────
const competitorData = [
  { name: "Faro Health", slug: "faro-health", category: "direct", website: "https://farohealth.com", description: "AI-powered clinical trial protocol design platform. Backed by BMS (Bristol Myers Squibb). Focuses on protocol authoring and feasibility. Direct overlap with Biorce's core protocol generation module.", fundingTotal: "$25M+", lastFundingRound: "Series A 2023", threatLevel: "critical", notes: "BMS partnership gives them a captive customer and validation. Risk: they become the BMS-exclusive standard. Biorce advantage: neutral infrastructure, multi-tenant, no pharma ownership." },
  { name: "Evinova", slug: "evinova", category: "direct", website: "https://evinova.com", description: "AstraZeneca spin-out offering digital health solutions for clinical trials including eCOA, eConsent, and trial design tools. Backed by AstraZeneca with $300M+ commitment.", fundingTotal: "$300M+", lastFundingRound: "AZ-backed 2023", threatLevel: "critical", notes: "AstraZeneca ownership is both their strength and their weakness. Biorce's neutral positioning is the counter-argument. Evinova cannot sell to Pfizer or Roche credibly." },
  { name: "Medidata (Dassault Systèmes)", slug: "medidata", category: "platform", website: "https://medidata.com", description: "Dominant EDC/eClinical platform acquired by Dassault Systèmes for $5.8B in 2019. Rave EDC is the industry standard. AI layer (Medidata AI) is bolt-on, not native. Partnership with Worldwide Clinical Trials announced April 2026.", fundingTotal: "Acquired $5.8B", lastFundingRound: "Dassault acquisition 2019", threatLevel: "high", notes: "Medidata is infrastructure, not intelligence. Biorce can partner OR compete depending on CIO appetite. WCT partnership (April 2026) means WCT is now a harder target for Biorce." },
  { name: "Veeva Systems", slug: "veeva", category: "platform", website: "https://veeva.com", description: "Life sciences cloud platform (Vault Clinical, SiteVault). $2B+ ARR. Moving into AI-assisted clinical operations. Strong regulatory submission capabilities.", fundingTotal: "Public (VEEV)", lastFundingRound: "Public", threatLevel: "high", notes: "Veeva Vault is the submission standard. Biorce needs to integrate with Vault, not compete with it. A Veeva partnership would give Biorce access to 1,000+ pharma customers." },
  { name: "Unlearn.AI", slug: "unlearn-ai", category: "adjacent", website: "https://unlearn.ai", description: "Digital twin technology for clinical trials — generates synthetic control arms to reduce placebo group sizes. FDA-accepted methodology. $50M+ raised.", fundingTotal: "$50M+", lastFundingRound: "Series B 2023", threatLevel: "medium", notes: "Adjacent, not direct. Potential partnership: Biorce generates the protocol, Unlearn.AI generates the synthetic controls. Complementary, not competitive." },
];

for (const c of competitorData) {
  await conn.execute(
    `INSERT IGNORE INTO competitors (name, slug, category, website, description, fundingTotal, lastFundingRound, threatLevel, notes) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    [c.name, c.slug, c.category, c.website, c.description, c.fundingTotal, c.lastFundingRound, c.threatLevel, c.notes]
  );
}
console.log("✓ Competitors seeded");

// ─── Regulatory Items ─────────────────────────────────────────────────────────
const regulatoryData = [
  { title: "FDA Digital Health Center of Excellence — AI/ML Action Plan Update", body: "FDA_DHCOE", type: "guidance", status: "active", description: "The FDA DHCoE published an updated AI/ML action plan requiring Predetermined Change Control Plans (PCCPs) for AI-based clinical decision support tools. Biorce's protocol generation AI may require a PCCP filing if positioned as a clinical decision support tool.", impactLevel: "critical", deadline: "2026-12-31", sourceUrl: "https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-and-machine-learning-software-medical-device", biorceRelevance: "Biorce must determine whether Aika 2.0 qualifies as a clinical decision support tool under FDA definitions. If yes, PCCP required. If positioned as a productivity tool (not clinical decision), different regulatory pathway." },
  { title: "ICH M11 Clinical Electronic Structured Harmonised Protocol (CeSHarP) — Final Guideline", body: "ICH_M11", type: "final_rule", status: "active", description: "ICH M11 establishes the international standard for structured clinical trial protocols. Adopted by FDA, EMA, and PMDA. Biorce's Aika platform must output protocols conformant with M11 structure to be accepted by regulators globally.", impactLevel: "critical", deadline: null, effectiveDate: "2025-01-01", sourceUrl: "https://www.ich.org/page/multidisciplinary-guidelines", biorceRelevance: "Biorce's first-mover claim (first AI-generated protocol submitted to FDA) depends on M11 compliance. This is a competitive moat: Biorce built M11 compliance natively; competitors are retrofitting." },
  { title: "CDISC Unified Study Definitions Model (USDM) v3.0", body: "CDISC_USDM", type: "guidance", status: "active", description: "CDISC USDM provides a machine-readable standard for clinical study definitions. TransCelerate's Digital Data Flow (DDF) initiative is built on USDM. FDA and EMA are moving toward USDM-based submissions.", impactLevel: "high", deadline: null, effectiveDate: "2025-06-01", sourceUrl: "https://www.cdisc.org/standards/foundational/usdm", biorceRelevance: "Biorce should output USDM-compliant structured data. This enables direct integration with sponsor EDC systems (Medidata, Veeva) and regulatory submission platforms. Key partnership enabler with TransCelerate." },
  { title: "EU AI Act — High-Risk AI Systems in Healthcare (Annex III)", body: "EU_AI_ACT", type: "final_rule", status: "active", description: "The EU AI Act classifies AI systems used in healthcare as high-risk under Annex III. Clinical trial protocol AI may qualify as high-risk, requiring conformity assessment, technical documentation, human oversight provisions, and registration in the EU AI database.", impactLevel: "critical", deadline: "2026-08-02", effectiveDate: "2026-08-02", sourceUrl: "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32024R1689", biorceRelevance: "CRITICAL DEADLINE: August 2, 2026. Biorce's Barcelona R&D center means EU AI Act applies directly. Must complete conformity assessment for Aika 2.0 if classified as high-risk. Legal counsel required immediately." },
  { title: "EMA Innovation Task Force (ITF) — AI in Clinical Trials Reflection Paper", body: "EMA_ITF", type: "guidance", status: "active", description: "EMA ITF published a reflection paper on the use of AI in clinical trial design and execution. Provides guidance on validation requirements, transparency obligations, and human oversight for AI-generated protocols.", impactLevel: "high", deadline: null, effectiveDate: "2025-09-01", sourceUrl: "https://www.ema.europa.eu/en/human-regulatory-overview/research-development/scientific-guidelines/clinical-trials-guidelines", biorceRelevance: "EMA ITF engagement is a strategic priority. A Letter of Support from EMA ITF for Biorce's methodology would be equivalent to FDA DHCoE endorsement in the EU market." },
  { title: "MHRA AI and Digital Technologies in Clinical Trials — Guidance", body: "MHRA", type: "guidance", status: "active", description: "UK MHRA published guidance on the use of AI and digital technologies in clinical trials following Brexit regulatory divergence. UK market requires separate compliance pathway.", impactLevel: "medium", deadline: null, effectiveDate: "2025-03-01", sourceUrl: "https://www.gov.uk/government/organisations/medicines-and-healthcare-products-regulatory-agency", biorceRelevance: "UK market is secondary to US and EU but strategically important for global pharma clients (GSK, AstraZeneca, Unilever). MHRA compliance enables UK-based clinical trials." },
];

for (const r of regulatoryData) {
  await conn.execute(
    `INSERT IGNORE INTO regulatory_items (title, body, type, status, description, impactLevel, deadline, effectiveDate, sourceUrl, alertSent, biorceRelevance) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, false, ?)`,
    [r.title, r.body, r.type, r.status, r.description, r.impactLevel, r.deadline ?? null, r.effectiveDate ?? null, r.sourceUrl, r.biorceRelevance]
  );
}
console.log("✓ Regulatory items seeded");

// ─── Knowledge Items ──────────────────────────────────────────────────────────
const knowledgeData = [
  { title: "Pedro Coelho — Itnig Podcast (2h interview, July 2025)", category: "podcast", sourceType: "primary", verificationStatus: "verified", sourceName: "Itnig Podcast", author: "Pedro Coelho", sourceUrl: "https://youtu.be/QCPlIkB-OkA", summary: "Comprehensive 2-hour interview covering Biorce's founding story, technical architecture, business model, fundraising journey, and future ambitions. Key revelations: (1) Model orchestrator architecture — not a single LLM but a routing layer that selects the optimal model per task; (2) Tenant isolation — RL happens inside client tenant, never on base models; (3) Pricing: $250K minimum, enterprise contracts in tens of millions; (4) ARR at Series A: $9.3M; (5) Acquisition offer near $2B rejected; (6) Revenue ambition: $10B+; (7) DeepMind head of research private briefing on reasoning model training; (8) Unannounced strategic partnership in progress ('hay cosas que no puedo decir que está pillado').", content: "Pedro describes the founding story rooted in his father's cancer treatment in Colombia — a personal mission that drives every strategic decision. The company was founded in Barcelona but is now primarily US-based with Austin as the commercial hub. The technical architecture centers on a model orchestrator that routes tasks to the optimal model (proprietary models for clinical tasks, public models for generic tasks like SQL). The 'accuracy' metric (starting at 68%, now 95%) measures the distance between Biorce's output and what the client actually submits — not a scientific accuracy measure. The pricing model is proprietary ('more secret than the model weights') based on number of trials, molecules, and people, with consumption on top. The Series A was not needed for cash (strong ARR) but for valuation to attract world-class talent. DST Global did 3 days of in-person shadowing before investing. Norrsken invested via a CLA with revenue multiples (10x-25x depending on ARR tranche). Pedro explicitly refused an acquisition offer near $2B because selling to one pharma would destroy the neutral infrastructure thesis.", tags: JSON.stringify(["architecture", "fundraising", "pricing", "strategy", "technical"]), entities: JSON.stringify(["Pedro Coelho", "Biorce", "DST Global", "Norrsken", "DeepMind", "Aika"]) },
  { title: "Pedro Coelho — EU Business School Interview: One-Click Clinical Trial", category: "public_statement", sourceType: "primary", verificationStatus: "verified", sourceName: "EU Business School", author: "Pedro Coelho", sourceUrl: "https://www.youtube.com/watch?v=zf3mYoiZcuE", summary: "Pedro articulates the north star vision: 'My greatest ambition is definitely to achieve a one-click clinical trial, and I believe we'll do it probably in the next coming years.' Also discusses product-led growth vs. founder-led sales: 'I do believe that product-led growth is the success for any startup, but equally one that has a very good sales system in place that allows you to scale that sales system in a non-founder-led sales version.' This is the explicit mandate for the Head of Partnerships role.", content: "Pedro discusses three pillars of founder success: perseverance, storytelling, and strategy. He emphasizes that Biorce needs to build a sales system that does not depend on him personally — this is the core mandate for the commercial team. The one-click clinical trial vision means a researcher can input a molecule and receive a complete, regulatory-compliant protocol ready for submission in one action. This requires solving protocol generation, amendment prediction, site selection, patient recruitment modeling, and regulatory submission in a single integrated workflow.", tags: JSON.stringify(["vision", "sales", "product-led-growth", "one-click"]), entities: JSON.stringify(["Pedro Coelho", "Biorce", "Aika"]) },
  { title: "Clara Bernardes — The Founder's Code (YouTube)", category: "podcast", sourceType: "primary", verificationStatus: "verified", sourceName: "The Founder's Code", author: "Clara Bernardes", sourceUrl: "https://www.youtube.com/watch?v=EeOvHwCWiLI", summary: "Clara discusses co-founder dynamics, hiring philosophy, and the 2035 vision. Key quote: 'Biorce is the standard and you have the possibility of doing a one-click clinical trial.' Hiring filter: 'Almost as a speed dating of a sort on how to make friends.' Values: Excellence, Ownership, Purpose, Ambition. Clara is Pedro's wife — the most important governance fact about Biorce. Winning Clara's trust is prerequisite to any strategic alliance.", content: "Clara describes the co-founder relationship and the importance of shared values over complementary skills. The hiring process is designed to filter for cultural fit as much as technical capability. She describes Biorce's 2035 vision as becoming the industry standard — not a feature, not a tool, but the infrastructure layer that every clinical trial runs on. The father's cancer story in Colombia is the emotional foundation of the company's mission.", tags: JSON.stringify(["culture", "hiring", "vision", "governance", "2035"]), entities: JSON.stringify(["Clara Bernardes", "Pedro Coelho", "Biorce"]) },
  { title: "Biorce Series A Press Release — €43.8M Funding", category: "press_release", sourceType: "primary", verificationStatus: "verified", sourceName: "Biorce Official", author: "Biorce", sourceUrl: "https://www.eu-startups.com/2026/02/barcelona-biorce-closes-e43-8-million-series-a-to-accelerate-ai-driven-clinical-trials/", summary: "Biorce closes €43.8M Series A led by DST Global with participation from Norrsken, TZR Capital, Nik Storonsky (Revolut founder), and Arthur Mensch (Mistral AI CEO). Funds earmarked for: US expansion (Austin hub), product development (Aika 2.0), and team growth from 130 to 200+. Austin office at 515/823 Congress Ave opened April 2026.", content: "The Series A validates Biorce's positioning as clinical AI infrastructure rather than a point solution. DST Global's participation (known for late-stage growth investments in Revolut, Klarna, Airbnb) signals institutional confidence in the $10B+ revenue ambition. The angel investors (Storonsky, Mensch) provide strategic credibility in fintech-grade AI infrastructure and frontier model development respectively. The Austin hub signals US-first commercial strategy with Barcelona retained for R&D and EU regulatory engagement.", tags: JSON.stringify(["fundraising", "series-a", "investors", "austin", "expansion"]), entities: JSON.stringify(["Biorce", "DST Global", "Norrsken", "TZR Capital", "Nik Storonsky", "Arthur Mensch", "Pedro Coelho"]) },
  { title: "Pedro Coelho — LinkedIn Post: Pharma Pays Tens of Millions for Protocol Amendments", category: "public_statement", sourceType: "primary", verificationStatus: "verified", sourceName: "LinkedIn", author: "Pedro Coelho", sourceUrl: "https://www.linkedin.com/posts/pmfccoelho_las-farmac%C3%A9uticas-pagan-decenas-de-millones-activity-7484986875464634369-mHXO", summary: "Pedro publicly states that pharmaceutical companies pay tens of millions for protocol amendments — the core pain point Biorce solves. This is the commercial wedge: amendment costs are measurable, attributable, and avoidable with Biorce. Used as the primary ROI argument in enterprise sales.", content: "Protocol amendments cost pharma companies $500K-$2M per amendment on average, with major trials experiencing 2-5 amendments. Biorce claims near-zero amendment rates for clients using Aika. The ROI calculation is straightforward: if a single amendment costs $1M and Biorce costs $500K/year, the payback period is less than one amendment cycle.", tags: JSON.stringify(["roi", "amendments", "commercial-wedge", "pharma"]), entities: JSON.stringify(["Pedro Coelho", "Biorce", "Aika"]) },
  { title: "Biorce — The End Talks: IQVIA Partnership Discussion (Pierre-Antoine André)", category: "podcast", sourceType: "primary", verificationStatus: "verified", sourceName: "The End Talks (Biorce)", author: "Pierre-Antoine André", sourceUrl: "https://www.biorce.com/media-hub", summary: "Pierre-Antoine André (IQVIA) discusses the future of CRO operations in an AI-first world. Key insight: 'CRO operations depend on human relationships — AI accelerates, trust is the foundation.' This validates Biorce's partnership-first commercial strategy. IQVIA is a potential channel partner (CRO) and potential competitive threat (if they build internally).", content: "The conversation explores how AI changes the CRO business model. André argues that the human relationship layer — site relationships, investigator trust, patient advocacy — cannot be automated. Biorce's AI handles the protocol and data layers while CROs retain the relationship layer. This is the partnership thesis: Biorce + CRO = faster trials, lower amendment rates, shared economics.", tags: JSON.stringify(["cro", "iqvia", "partnership", "trust", "relationships"]), entities: JSON.stringify(["Pierre-Antoine André", "IQVIA", "Biorce", "Pedro Coelho"]) },
  { title: "Biorce — First AI-Generated Protocol Submitted to FDA", category: "press_release", sourceType: "primary", verificationStatus: "verified", sourceName: "Biorce Official", author: "Biorce", sourceUrl: "https://www.biorce.com/media-hub", summary: "Biorce became the first company to submit an AI-generated clinical trial protocol to the FDA. This is the single most powerful US credibility anchor. It validates the technology, demonstrates regulatory acceptance, and creates a defensible first-mover claim that competitors cannot replicate retroactively.", content: "The FDA submission represents a landmark in clinical AI. The protocol was generated by Aika, reviewed by the client's medical team, and submitted without material amendments. The FDA's acceptance (not rejection) of the submission validates the methodology. This event should be the centerpiece of every US enterprise sales conversation.", tags: JSON.stringify(["fda", "first-mover", "credibility", "us-market"]), entities: JSON.stringify(["Biorce", "FDA", "Aika", "Pedro Coelho"]) },
  { title: "Biorce — Aika 2.0 Launch at ASCO 2026 and BIO 2026", category: "press_release", sourceType: "primary", verificationStatus: "verified", sourceName: "Biorce Official", author: "Biorce", sourceUrl: "https://www.biorce.com/media-hub", summary: "Aika 2.0 launched at ASCO 2026 (Chicago) and BIO 2026 (San Diego) using private demo rides instead of traditional conference booths. This is a deliberate positioning choice: Biorce does not compete for attention at conferences, it commands it. The private ride format creates exclusivity and filters for serious buyers.", content: "The ASCO and BIO launches mark Biorce's formal entry into the US enterprise market. The private demo ride format (Uber-style private meetings during conference) is a commercial strategy that signals premium positioning and creates urgency. Aika 2.0 includes enhanced protocol generation, amendment prediction, and regulatory submission support.", tags: JSON.stringify(["aika-2.0", "asco", "bio", "product-launch", "us-market"]), entities: JSON.stringify(["Biorce", "Aika", "Pedro Coelho", "Clara Bernardes"]) },
  { title: "Faro Health — BMS Partnership and Series A Funding", category: "competitor", sourceType: "primary", verificationStatus: "verified", sourceName: "Faro Health Press Release", author: "Faro Health", sourceUrl: "https://farohealth.com", summary: "Faro Health secured a strategic partnership with Bristol Myers Squibb and raised Series A funding. BMS integration gives Faro a captive customer and validation. Risk for Biorce: Faro becomes the BMS-exclusive standard, blocking Biorce from BMS. Opportunity: Faro's BMS ownership makes it unsellable to Pfizer, Roche, or Lilly.", content: "Faro Health's BMS partnership is both a validation and a limitation. It validates the market for AI protocol design but creates a conflict of interest that prevents Faro from becoming neutral infrastructure. Biorce's counter-positioning: 'We are the only neutral infrastructure provider. Faro is BMS's tool. Evinova is AstraZeneca's tool. Biorce belongs to no one.'", tags: JSON.stringify(["faro-health", "bms", "competitor", "partnership"]), entities: JSON.stringify(["Faro Health", "Bristol Myers Squibb", "Biorce"]) },
  { title: "Evinova — AstraZeneca Spin-out and $300M Commitment", category: "competitor", sourceType: "primary", verificationStatus: "verified", sourceName: "AstraZeneca Press Release", author: "AstraZeneca", sourceUrl: "https://evinova.com", summary: "Evinova launched as an AstraZeneca spin-out with $300M+ commitment. Offers eCOA, eConsent, and trial design tools. Direct competitor to Biorce in protocol design. AstraZeneca ownership prevents Evinova from being adopted by competing pharma companies.", content: "Evinova's AstraZeneca backing gives it resources and credibility but creates a fundamental commercial constraint: no Pfizer, Roche, Lilly, or Novartis will adopt a tool owned by their competitor. Biorce's neutral positioning is the direct counter-argument to Evinova in every enterprise sales conversation.", tags: JSON.stringify(["evinova", "astrazeneca", "competitor", "neutral-positioning"]), entities: JSON.stringify(["Evinova", "AstraZeneca", "Biorce"]) },
];

for (const k of knowledgeData) {
  await conn.execute(
    `INSERT IGNORE INTO knowledge_items (title, content, summary, category, sourceType, verificationStatus, sourceName, author, sourceUrl, tags, entities, isConfidential) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, false)`,
    [k.title, k.content, k.summary, k.category, k.sourceType, k.verificationStatus, k.sourceName, k.author, k.sourceUrl, k.tags, k.entities]
  );
}
console.log("✓ Knowledge items seeded");

// ─── Partners (50 Priority Targets) ──────────────────────────────────────────
const partnerData = [
  // P0 — Must close in 12 months
  { name: "Isomorphic Labs / Google DeepMind", type: "tech", tier: "P0", stage: "researching", region: "GLOBAL", website: "https://isomorphiclabs.com", description: "Google DeepMind's drug discovery AI company. Pedro received a private briefing from DeepMind's head of research on reasoning model training. Natural infrastructure partner: Biorce handles clinical trial design, Isomorphic handles molecular discovery.", mutualValue: "Biorce provides the clinical trial infrastructure layer for Isomorphic's drug candidates. Isomorphic provides AI research credibility and potential Google Cloud distribution.", dealEconomics: "Technology partnership + co-marketing. Revenue share on joint customers.", killCriteria: "Google acquires a direct Biorce competitor. Isomorphic builds internal protocol AI.", nextAction: "Warm intro via Arthur Mensch (Mistral AI, Biorce angel investor) to Demis Hassabis.", estimatedArrImpact: "$5M+" },
  { name: "FDA Digital Health Center of Excellence", type: "regulator", tier: "P0", stage: "outreach", region: "US", website: "https://www.fda.gov/medical-devices/digital-health-center-excellence", description: "FDA's center for digital health innovation. A Letter of Support from FDA DHCoE for Biorce's AI methodology would eliminate the compliance veto in every US enterprise sale.", mutualValue: "Biorce provides real-world evidence of AI-generated protocol quality. FDA gets a case study for AI in clinical trials guidance.", dealEconomics: "Non-commercial. Strategic credibility asset.", killCriteria: "FDA issues guidance that classifies Biorce's AI as a regulated medical device requiring PMA.", nextAction: "Submit a formal briefing document to FDA DHCoE citing the first AI-generated protocol submission. Request a Type B meeting.", estimatedArrImpact: "Unlocks $50M+ in blocked enterprise deals" },
  { name: "Eli Lilly", type: "pharma", tier: "P0", stage: "researching", region: "US", website: "https://lilly.com", description: "Top-5 global pharma. 50+ active clinical trials. Diogo Rau is EVP & Chief Information and Digital Officer. Lilly's 30x30 initiative (30 new medicines by 2030) creates massive protocol generation demand.", mutualValue: "Biorce reduces Lilly's protocol amendment rate and accelerates trial initiation. Lilly provides Biorce with a marquee US pharma reference customer.", dealEconomics: "Enterprise SaaS: $2-5M/year. Potential multi-year infrastructure contract.", killCriteria: "Lilly acquires Faro Health or builds internal protocol AI. Diogo Rau leaves.", nextAction: "Outreach to Diogo Rau (EVP CIDO) via LinkedIn. Reference the 30x30 initiative and the FDA first-submission milestone.", estimatedArrImpact: "$3-5M ARR" },
  { name: "TriNetX", type: "tech", tier: "P0", stage: "researching", region: "US", website: "https://trinetx.com", description: "Real-world data network connecting 150+ health systems globally. Biorce generates the protocol; TriNetX provides the patient population data for feasibility. Natural integration partner.", mutualValue: "Joint offering: AI protocol + real-world feasibility data. Reduces time from protocol to site selection by 60%.", dealEconomics: "Revenue share on joint customers. Integration partnership.", killCriteria: "TriNetX acquired by Medidata or Veeva.", nextAction: "Contact TriNetX BD team. Propose a joint demo for top-10 pharma clients.", estimatedArrImpact: "$2-4M ARR via channel" },
  // P1 — Target in months 3-9
  { name: "Roche / Genentech", type: "pharma", tier: "P1", stage: "identified", region: "GLOBAL", website: "https://roche.com", description: "Largest oncology pharma globally. Wafaa Mamilli is Chief Digital and Technology Officer (17 months in role — ideal window). 100+ active oncology trials.", mutualValue: "Biorce's oncology protocol expertise (ASCO launch) aligns with Roche's core therapeutic area.", dealEconomics: "Enterprise SaaS: $3-8M/year.", killCriteria: "Roche deepens Evinova partnership (AZ competitor relationship makes this unlikely).", nextAction: "Outreach to Wafaa Mamilli. Reference ASCO 2026 Aika 2.0 launch and oncology protocol expertise.", estimatedArrImpact: "$5-8M ARR" },
  { name: "Novartis", type: "pharma", tier: "P1", stage: "identified", region: "GLOBAL", website: "https://novartis.com", description: "Top-5 global pharma. Sander Timmer leads AI initiatives. Novartis has publicly committed to AI-first drug development.", mutualValue: "Biorce accelerates Novartis's AI-first clinical development ambition.", dealEconomics: "Enterprise SaaS: $2-5M/year.", killCriteria: "Novartis builds internal protocol AI (they have the engineering capacity).", nextAction: "Outreach to Sander Timmer via LinkedIn. Reference Novartis's AI-first commitment.", estimatedArrImpact: "$3-5M ARR" },
  { name: "Pfizer", type: "pharma", tier: "P1", stage: "identified", region: "US", website: "https://pfizer.com", description: "Largest pharma by revenue. Lidia Fonseca is Chief Digital and Technology Officer. Post-COVID, Pfizer is investing heavily in digital clinical operations.", mutualValue: "Biorce reduces Pfizer's protocol amendment costs (estimated $50M+/year across portfolio).", dealEconomics: "Enterprise SaaS: $5-10M/year.", killCriteria: "Pfizer acquires a direct competitor.", nextAction: "Outreach to Lidia Fonseca. Lead with the amendment cost reduction ROI.", estimatedArrImpact: "$5-10M ARR" },
  { name: "AstraZeneca", type: "pharma", tier: "P1", stage: "identified", region: "GLOBAL", website: "https://astrazeneca.com", description: "AZ owns Evinova — a direct Biorce competitor. However, Evinova focuses on eCOA/eConsent, not protocol generation. There may be a complementary layer above Evinova.", mutualValue: "Biorce handles protocol generation; Evinova handles patient-facing digital tools. Non-overlapping.", dealEconomics: "Potential OEM or integration partnership with Evinova.", killCriteria: "Evinova expands into protocol generation.", nextAction: "Approach AZ's clinical operations team (not Evinova) about protocol generation above the Evinova layer.", estimatedArrImpact: "$2-3M ARR" },
  { name: "Johnson & Johnson (Janssen)", type: "pharma", tier: "P1", stage: "identified", region: "US", website: "https://jnj.com", description: "Top-3 pharma. Strong oncology and immunology pipeline. Active in digital health innovation.", mutualValue: "Biorce reduces J&J's protocol amendment costs across its 200+ active trials.", dealEconomics: "Enterprise SaaS: $3-7M/year.", killCriteria: "J&J acquires a direct competitor.", nextAction: "Identify J&J's Chief Digital Officer and clinical operations leadership.", estimatedArrImpact: "$4-7M ARR" },
  { name: "Bristol Myers Squibb", type: "pharma", tier: "P1", stage: "identified", region: "US", website: "https://bms.com", description: "BMS is Faro Health's strategic partner — a direct Biorce competitor. However, BMS may want a second vendor for protocol AI to avoid single-vendor dependency.", mutualValue: "Biorce offers BMS a neutral alternative to Faro, reducing vendor lock-in risk.", dealEconomics: "Enterprise SaaS: $2-4M/year.", killCriteria: "BMS deepens Faro exclusivity. BMS acquires Faro.", nextAction: "Approach BMS's clinical operations team with a 'vendor diversification' narrative.", estimatedArrImpact: "$2-4M ARR" },
  { name: "Parexel", type: "cro", tier: "P1", stage: "identified", region: "US", website: "https://parexel.com", description: "Top-3 CRO globally. Peyton Howell is CEO. Parexel has no proprietary AI protocol platform — a gap Biorce can fill as a white-label or channel partner.", mutualValue: "Biorce gives Parexel an AI protocol capability to sell to clients. Parexel gives Biorce access to 500+ pharma clients.", dealEconomics: "Revenue share: 20-30% of contract value on Parexel-sourced clients.", killCriteria: "Parexel acquires Faro Health or builds internal protocol AI.", nextAction: "Outreach to Peyton Howell. Propose a white-label partnership.", estimatedArrImpact: "$5-10M ARR via channel" },
  { name: "ICON plc", type: "cro", tier: "P1", stage: "identified", region: "GLOBAL", website: "https://iconplc.com", description: "Top-5 CRO. Strong in oncology and rare disease. No proprietary AI protocol platform.", mutualValue: "Same as Parexel — Biorce as AI layer for ICON's clinical operations.", dealEconomics: "Revenue share: 20-30%.", killCriteria: "ICON acquires a direct competitor.", nextAction: "Identify ICON's Chief Digital Officer.", estimatedArrImpact: "$3-6M ARR via channel" },
  { name: "Veeva Systems", type: "tech", tier: "P1", stage: "identified", region: "US", website: "https://veeva.com", description: "Vault Clinical is the submission standard. A Veeva integration gives Biorce access to 1,000+ pharma customers. Veeva is a platform, not a competitor.", mutualValue: "Biorce generates the protocol; Veeva Vault submits it. End-to-end workflow.", dealEconomics: "Technology integration partnership. Co-selling agreement.", killCriteria: "Veeva builds native AI protocol generation.", nextAction: "Approach Veeva's partnership team. Propose a Vault Clinical integration.", estimatedArrImpact: "Unlocks $20M+ in pipeline via Veeva customer base" },
  { name: "Worldwide Clinical Trials", type: "cro", tier: "P1", stage: "identified", region: "US", website: "https://worldwideclinicaltrials.com", description: "Mid-size CRO with strong oncology focus. Alistair Macdonald is CEO. NOTE: WCT signed a Medidata partnership in April 2026 — Biorce must position as a complementary layer above Medidata, not a replacement.", mutualValue: "Biorce handles protocol generation; Medidata handles data collection. Non-overlapping.", dealEconomics: "Revenue share on protocol generation services.", killCriteria: "WCT deepens Medidata exclusivity to include protocol generation.", nextAction: "Approach WCT with a 'protocol generation above Medidata' positioning.", estimatedArrImpact: "$1-3M ARR" },
  // P2 — Target in months 6-18
  { name: "Dell Medical School / UT Austin", type: "hospital", tier: "P2", stage: "identified", region: "US", website: "https://dellmed.utexas.edu", description: "Austin's premier academic medical center. Natural first US academic partner given Biorce's Austin HQ. Provides clinical trial credibility and investigator relationships.", mutualValue: "Biorce provides AI protocol tools for Dell Medical's clinical research. Dell Medical provides Biorce with academic validation and investigator network.", dealEconomics: "Institutional license: $100-250K/year.", killCriteria: "Dell Medical adopts a competing platform.", nextAction: "Leverage Austin network to arrange intro to Dell Medical's research office.", estimatedArrImpact: "$200K ARR + strategic value" },
  { name: "MD Anderson Cancer Center", type: "hospital", tier: "P2", stage: "identified", region: "US", website: "https://mdanderson.org", description: "World's leading cancer research center. 1,000+ active clinical trials. An MD Anderson reference would be the most powerful US academic validation possible.", mutualValue: "Biorce reduces MD Anderson's protocol amendment burden. MD Anderson provides Biorce with oncology protocol expertise and reference.", dealEconomics: "Institutional license: $500K-1M/year.", killCriteria: "MD Anderson adopts Faro Health.", nextAction: "Identify MD Anderson's VP of Research and clinical trials office leadership.", estimatedArrImpact: "$500K-1M ARR + strategic value" },
  { name: "Mayo Clinic", type: "hospital", tier: "P2", stage: "identified", region: "US", website: "https://mayoclinic.org", description: "Top US academic medical center. Strong clinical research program. Mayo Clinic Platform is their digital health initiative.", mutualValue: "Biorce integrates with Mayo Clinic Platform for protocol generation.", dealEconomics: "Institutional license: $500K-1M/year.", killCriteria: "Mayo Clinic Platform builds internal protocol AI.", nextAction: "Approach Mayo Clinic Platform leadership.", estimatedArrImpact: "$500K-1M ARR" },
  { name: "TransCelerate BioPharma", type: "standards_body", tier: "P2", stage: "identified", region: "GLOBAL", website: "https://transceleratebiopharmainc.com", description: "Non-profit consortium of 20+ pharma companies driving clinical trial innovation. Their Digital Data Flow (DDF) initiative is built on CDISC USDM. Biorce USDM compliance enables DDF integration.", mutualValue: "Biorce provides AI-generated USDM-compliant protocols for DDF. TransCelerate validates Biorce's standards compliance.", dealEconomics: "Non-commercial. Strategic standards body membership.", killCriteria: "TransCelerate endorses a competing platform.", nextAction: "Apply for TransCelerate membership. Attend DDF working group meetings.", estimatedArrImpact: "Unlocks access to 20+ pharma members" },
  { name: "CDISC", type: "standards_body", tier: "P2", stage: "identified", region: "GLOBAL", website: "https://cdisc.org", description: "Clinical Data Interchange Standards Consortium. USDM is their standard. CDISC endorsement of Biorce's USDM compliance would be a powerful validator.", mutualValue: "Biorce demonstrates USDM in production at scale. CDISC gets a reference implementation.", dealEconomics: "Non-commercial. Standards body relationship.", killCriteria: "CDISC endorses a competing platform.", nextAction: "Engage CDISC's technology partnerships team.", estimatedArrImpact: "Standards credibility multiplier" },
  { name: "Norrsken VC (Existing Investor)", type: "investor", tier: "P2", stage: "active", region: "EU", website: "https://norrsken.org", description: "Existing Biorce investor. Norrsken's portfolio includes 100+ impact startups. Potential to introduce Biorce to Norrsken portfolio pharma and health companies.", mutualValue: "Biorce leverages Norrsken's network for EU partnerships. Norrsken gets portfolio company synergies.", dealEconomics: "Existing relationship. No new economics needed.", killCriteria: "N/A — existing investor.", nextAction: "Request a portfolio introduction session from Norrsken.", estimatedArrImpact: "EU pipeline acceleration" },
];

for (const p of partnerData) {
  const [result] = await conn.execute(
    `INSERT IGNORE INTO partners (name, type, tier, stage, region, website, description, mutualValue, dealEconomics, killCriteria, nextAction, estimatedArrImpact) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    [p.name, p.type, p.tier, p.stage, p.region, p.website, p.description, p.mutualValue, p.dealEconomics, p.killCriteria, p.nextAction, p.estimatedArrImpact]
  );
}
console.log("✓ Partners seeded");

// ─── Discrepancies ────────────────────────────────────────────────────────────
const discrepancyData = [
  { title: "EU AI Act Compliance Deadline: August 2, 2026 — No Public Biorce Response", type: "regulatory_conflict", severity: "critical", status: "open", description: "The EU AI Act's high-risk AI provisions become enforceable on August 2, 2026. Biorce's Barcelona R&D center means EU jurisdiction applies. Biorce has made no public statement about EU AI Act compliance status for Aika 2.0. If Aika qualifies as a high-risk AI system under Annex III (AI in healthcare), a conformity assessment is required before the deadline.", sourceA: "EU AI Act, Regulation (EU) 2024/1689, Article 6 and Annex III", sourceB: "Biorce public communications — no mention of EU AI Act compliance" },
  { title: "Accuracy Metric (95%) — Definition Inconsistency in Public Communications", type: "internal_vs_public", severity: "high", status: "open", description: "Biorce publicly references '95% accuracy' for Aika. However, Pedro clarified in the Itnig podcast that this measures 'the distance between Biorce's output and what the client actually submits' — not scientific accuracy. External audiences may interpret this as a scientific validation metric, creating a potential misrepresentation risk.", sourceA: "Biorce marketing materials: '95% accuracy'", sourceB: "Pedro Coelho, Itnig Podcast: 'It measures the distance between what we deliver and what they submit'" },
  { title: "WCT Partnership: Medidata April 2026 vs. Biorce Pipeline Target", type: "strategy_drift", severity: "high", status: "open", description: "Worldwide Clinical Trials (WCT) signed a strategic partnership with Medidata in April 2026. Biorce's partnership playbook lists WCT as a P1 CRO target. The Medidata partnership changes the approach: Biorce must now position as a complementary layer above Medidata, not a replacement.", sourceA: "Biorce partnership playbook: WCT as P1 CRO target", sourceB: "Medidata press release, April 2026: WCT-Medidata strategic partnership" },
  { title: "Acquisition Offer Refusal — Undisclosed Acquirer Creates Relationship Risk", type: "competitor_claim", severity: "medium", status: "open", description: "Pedro confirmed in the Itnig podcast that Biorce received an acquisition offer 'not far from $2B' which was refused. The acquirer was not named. If the acquirer was a major pharma (likely), that company may now be incentivized to accelerate a competing internal build or acquire Faro Health.", sourceA: "Pedro Coelho, Itnig Podcast: acquisition offer refused, acquirer unnamed", sourceB: "No public information on acquirer identity" },
  { title: "Barcelona vs. Austin: R&D/Commercial Split Creates Regulatory Jurisdiction Complexity", type: "strategy_drift", severity: "medium", status: "investigating", description: "Biorce operates R&D in Barcelona (EU jurisdiction, EU AI Act, GDPR) and commercial operations in Austin (US jurisdiction, FDA). This dual jurisdiction creates compliance complexity: EU AI Act applies to Barcelona R&D; FDA guidance applies to US commercial operations. The same AI model may face different regulatory requirements in each jurisdiction.", sourceA: "Biorce public communications: Austin commercial hub, Barcelona R&D", sourceB: "EU AI Act territorial scope; FDA AI/ML guidance" },
];

for (const d of discrepancyData) {
  await conn.execute(
    `INSERT IGNORE INTO discrepancies (title, description, type, severity, status, sourceA, sourceB) VALUES (?, ?, ?, ?, ?, ?, ?)`,
    [d.title, d.description, d.type, d.severity, d.status, d.sourceA, d.sourceB]
  );
}
console.log("✓ Discrepancies seeded");

// ─── Alerts ───────────────────────────────────────────────────────────────────
const alertData = [
  { type: "regulatory", title: "CRITICAL: EU AI Act enforcement begins August 2, 2026", body: "The EU AI Act's high-risk AI provisions become enforceable in 2 days. Biorce has made no public statement about compliance status for Aika 2.0. Immediate legal review required to determine if Aika qualifies as high-risk under Annex III.", severity: "critical", isRead: false },
  { type: "competitive", title: "Faro Health: New partnership announcement expected Q3 2026", body: "Intelligence suggests Faro Health is in advanced discussions with a second top-10 pharma partner beyond BMS. If confirmed, this would significantly strengthen Faro's market position. Monitor Faro Health press releases and LinkedIn activity.", severity: "high", isRead: false },
  { type: "partnership", title: "Eli Lilly 30x30 Initiative: Protocol generation demand spike", body: "Eli Lilly's 30x30 initiative (30 new medicines by 2030) requires 30+ new clinical trial protocols in the next 4 years. This is a direct Biorce opportunity. Diogo Rau (EVP CIDO) is the primary contact. Outreach window is now.", severity: "high", isRead: false },
  { type: "regulatory", title: "ICH M11 Final Guideline: Compliance verification required", body: "ICH M11 CeSHarP final guideline is now in effect. Biorce's first-mover claim depends on verified M11 compliance. Recommend publishing a technical white paper demonstrating Aika 2.0's M11 compliance to use as a sales asset.", severity: "medium", isRead: false },
  { type: "competitive", title: "Medidata-WCT Partnership: Adjust WCT approach strategy", body: "Worldwide Clinical Trials signed a Medidata partnership in April 2026. Update WCT partnership approach: position Biorce as protocol generation layer above Medidata, not as a replacement. Revise outreach messaging accordingly.", severity: "medium", isRead: true },
  { type: "digest", title: "Weekly Intelligence Digest — Week of July 28, 2026", body: "REGULATORY: EU AI Act enforcement in 2 days — critical action required. COMPETITIVE: No new Faro or Evinova announcements this week. PARTNERSHIPS: Lilly 30x30 initiative creates immediate outreach opportunity. DISCREPANCIES: 5 open flags, 1 critical (EU AI Act). KNOWLEDGE BASE: 10 verified intelligence items loaded.", severity: "medium", isRead: false },
];

for (const a of alertData) {
  await conn.execute(
    `INSERT IGNORE INTO alerts (type, title, body, severity, isRead) VALUES (?, ?, ?, ?, ?)`,
    [a.type, a.title, a.body, a.severity, a.isRead]
  );
}
console.log("✓ Alerts seeded");

// ─── Graph Nodes & Edges ──────────────────────────────────────────────────────
const nodeData = [
  { label: "Biorce", type: "company" }, { label: "Pedro Coelho", type: "person" }, { label: "Clara Bernardes", type: "person" },
  { label: "Diogo Coelho", type: "person" }, { label: "José Coelho", type: "person" }, { label: "DST Global", type: "company" },
  { label: "Norrsken VC", type: "company" }, { label: "Nik Storonsky", type: "person" }, { label: "Arthur Mensch", type: "person" },
  { label: "Aika 2.0", type: "product" }, { label: "FDA DHCoE", type: "regulator" }, { label: "EMA ITF", type: "regulator" },
  { label: "EU AI Act", type: "standard" }, { label: "ICH M11", type: "standard" }, { label: "CDISC USDM", type: "standard" },
  { label: "Faro Health", type: "company" }, { label: "Evinova", type: "company" }, { label: "Medidata", type: "company" },
  { label: "Unlearn.AI", type: "company" }, { label: "Veeva Systems", type: "company" }, { label: "Eli Lilly", type: "company" },
  { label: "Roche", type: "company" }, { label: "Novartis", type: "company" }, { label: "Pfizer", type: "company" },
  { label: "Parexel", type: "company" }, { label: "IQVIA", type: "company" }, { label: "Isomorphic Labs", type: "company" },
  { label: "TriNetX", type: "company" }, { label: "TransCelerate", type: "company" }, { label: "Bristol Myers Squibb", type: "company" },
];

const nodeIds = {};
for (const n of nodeData) {
  const [result] = await conn.execute(`INSERT IGNORE INTO graph_nodes (label, type) VALUES (?, ?)`, [n.label, n.type]);
  if (result.insertId) nodeIds[n.label] = result.insertId;
}
// Re-fetch IDs for existing nodes
const [existingNodes] = await conn.execute(`SELECT id, label FROM graph_nodes`);
for (const row of existingNodes) nodeIds[row.label] = row.id;

const edgeData = [
  { source: "Pedro Coelho", target: "Biorce", relationship: "co-founded", verificationStatus: "verified" },
  { source: "Clara Bernardes", target: "Biorce", relationship: "co-founded", verificationStatus: "verified" },
  { source: "Pedro Coelho", target: "Clara Bernardes", relationship: "married to", verificationStatus: "verified" },
  { source: "Biorce", target: "Aika 2.0", relationship: "built", verificationStatus: "verified" },
  { source: "DST Global", target: "Biorce", relationship: "invested in (Series A)", verificationStatus: "verified" },
  { source: "Norrsken VC", target: "Biorce", relationship: "invested in (Seed + Series A)", verificationStatus: "verified" },
  { source: "Nik Storonsky", target: "Biorce", relationship: "angel investor", verificationStatus: "verified" },
  { source: "Arthur Mensch", target: "Biorce", relationship: "angel investor", verificationStatus: "verified" },
  { source: "Aika 2.0", target: "FDA DHCoE", relationship: "first AI protocol submitted to", verificationStatus: "verified" },
  { source: "Aika 2.0", target: "ICH M11", relationship: "compliant with", verificationStatus: "verified" },
  { source: "Faro Health", target: "Bristol Myers Squibb", relationship: "strategic partner", verificationStatus: "verified" },
  { source: "Evinova", target: "Roche", relationship: "owned by AstraZeneca (competitor)", verificationStatus: "inferred" },
  { source: "Biorce", target: "IQVIA", relationship: "potential CRO partner", verificationStatus: "inferred" },
  { source: "Biorce", target: "Eli Lilly", relationship: "priority target (P0)", verificationStatus: "verified" },
  { source: "Biorce", target: "Isomorphic Labs", relationship: "potential tech partner (DeepMind connection)", verificationStatus: "inferred" },
  { source: "Medidata", target: "Worldwide Clinical Trials", relationship: "strategic partner (April 2026)", verificationStatus: "verified" },
  { source: "Biorce", target: "EU AI Act", relationship: "subject to (Barcelona R&D)", verificationStatus: "verified" },
  { source: "Biorce", target: "TransCelerate", relationship: "USDM compliance target", verificationStatus: "inferred" },
];

for (const e of edgeData) {
  const sourceId = nodeIds[e.source];
  const targetId = nodeIds[e.target];
  if (sourceId && targetId) {
    await conn.execute(
      `INSERT IGNORE INTO graph_edges (sourceId, targetId, relationship, verificationStatus) VALUES (?, ?, ?, ?)`,
      [sourceId, targetId, e.relationship, e.verificationStatus]
    );
  }
}
console.log("✓ Graph nodes and edges seeded");

await conn.end();
console.log("\n✅ All Biorce intelligence data seeded successfully.");
