CREATE TABLE `job_executions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`jobName` varchar(128) NOT NULL,
	`taskUid` varchar(128),
	`idempotencyKey` varchar(256) NOT NULL,
	`inFlight` boolean NOT NULL DEFAULT false,
	`status` enum('running','success','failed','skipped') NOT NULL DEFAULT 'running',
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	`durationMs` int,
	`recordsRead` int DEFAULT 0,
	`recordsWritten` int DEFAULT 0,
	`alertsCreated` int DEFAULT 0,
	`attemptNumber` int NOT NULL DEFAULT 1,
	`maxAttempts` int NOT NULL DEFAULT 3,
	`errorMessage` text,
	`errorStack` text,
	`escalated` boolean NOT NULL DEFAULT false,
	`escalationNote` text,
	`triggeredBy` varchar(64) NOT NULL DEFAULT 'cron',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `job_executions_id` PRIMARY KEY(`id`),
	CONSTRAINT `job_executions_idempotencyKey_unique` UNIQUE(`idempotencyKey`)
);
