CREATE TABLE `decision_room_candidates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`token` varchar(64) NOT NULL,
	`userOpenId` varchar(256) NOT NULL,
	`question` text NOT NULL,
	`gateConfidence` int,
	`gateMateriality` varchar(32),
	`gateRationale` text,
	`gateVersion` varchar(32),
	`gateAlternatives` json,
	`gateProposedOwner` varchar(256),
	`gateProposedDeadline` varchar(64),
	`duplicateRoomId` int,
	`duplicateSimilarity` int,
	`duplicateStatus` varchar(64),
	`duplicateQuestion` text,
	`consumed` boolean NOT NULL DEFAULT false,
	`consumedAt` timestamp,
	`resultingRoomId` int,
	`expiresAt` timestamp NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `decision_room_candidates_id` PRIMARY KEY(`id`),
	CONSTRAINT `decision_room_candidates_token_unique` UNIQUE(`token`)
);
