import AppLayout from "@/components/AppLayout";
import { trpc } from "@/lib/trpc";
import { Download, FileText, Loader2 } from "lucide-react";
import { useRef, useState } from "react";
import { toast } from "sonner";

export default function BoardMemo() {
  const [html, setHtml] = useState<string | null>(null);
  const [generatedAt, setGeneratedAt] = useState<string | null>(null);
  const printRef = useRef<HTMLDivElement>(null);
    const generate = trpc.boardMemo.generate.useMutation({
      onSuccess: (data) => {
        setHtml(typeof data.html === "string" ? data.html : String(data.html ?? ""));
        setGeneratedAt(data.generatedAt);
      },
    onError: () => toast.error("Failed to generate memo. Please try again."),
    });

  const handlePrint = () => {
    const printWindow = window.open("", "_blank");
    if (!printWindow || !html) return;
    printWindow.document.write(`<!DOCTYPE html><html><head><title>Biorce Board Intelligence Memo</title><style>
      body { font-family: 'Georgia', serif; max-width: 800px; margin: 40px auto; padding: 0 40px; color: #1a1a2e; line-height: 1.6; }
      h1 { font-size: 24px; border-bottom: 2px solid #0d9488; padding-bottom: 12px; margin-bottom: 24px; }
      h2 { font-size: 18px; color: #0d9488; margin-top: 32px; margin-bottom: 12px; border-left: 3px solid #0d9488; padding-left: 12px; }
      p { margin-bottom: 12px; }
      ul { margin: 8px 0 16px 20px; }
      li { margin-bottom: 6px; }
      .footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #ccc; font-size: 12px; color: #666; }
      @media print { body { margin: 20px; } }
    </style></head><body>${html}<div class="footer">Generated by Biorce Strategy Copilot — ${new Date(generatedAt!).toLocaleString()} — CONFIDENTIAL</div></body></html>`);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <AppLayout>
      <div className="p-6 max-w-4xl mx-auto">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg flex items-center justify-center" style={{ background: "var(--color-primary)" }}>
              <FileText className="w-4 h-4" style={{ color: "var(--color-primary-foreground)" }} />
            </div>
            <div>
              <h1 className="text-base font-semibold" style={{ color: "var(--color-foreground)" }}>Board Intelligence Memo</h1>
              <p className="text-xs" style={{ color: "var(--color-muted-foreground)" }}>AI-generated executive briefing from verified knowledge base</p>
            </div>
          </div>
          <div className="flex gap-2">
            {html && (
              <button onClick={handlePrint}
                className="flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-medium border transition-all active:scale-95"
                style={{ background: "var(--color-card)", borderColor: "var(--color-border)", color: "var(--color-foreground)" }}>
                <Download className="w-3.5 h-3.5" />
                Print / Save PDF
              </button>
            )}
            <button onClick={() => generate.mutate({ sections: [] })} disabled={generate.isPending}
              className="flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-medium transition-all active:scale-95 disabled:opacity-60"
              style={{ background: "var(--color-primary)", color: "var(--color-primary-foreground)" }}>
              {generate.isPending ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <FileText className="w-3.5 h-3.5" />}
              {generate.isPending ? "Generating..." : html ? "Regenerate" : "Generate Memo"}
            </button>
          </div>
        </div>

        {!html && !generate.isPending && (
          <div className="flex flex-col items-center justify-center py-24 gap-4">
            <div className="w-16 h-16 rounded-2xl flex items-center justify-center" style={{ background: "var(--color-accent)" }}>
              <FileText className="w-8 h-8" style={{ color: "var(--color-muted-foreground)" }} />
            </div>
            <p className="text-sm text-center" style={{ color: "var(--color-muted-foreground)" }}>
              Click "Generate Memo" to create an AI-drafted board intelligence briefing<br />
              covering regulatory, competitive, partnership, and discrepancy intelligence.
            </p>
          </div>
        )}

        {generate.isPending && (
          <div className="flex flex-col items-center justify-center py-24 gap-4">
            <Loader2 className="w-10 h-10 animate-spin" style={{ color: "var(--color-primary)" }} />
            <p className="text-sm" style={{ color: "var(--color-muted-foreground)" }}>Synthesizing intelligence from verified knowledge base...</p>
          </div>
        )}

        {html && !generate.isPending && (
          <div ref={printRef} className="rounded-xl border p-8" style={{ background: "var(--color-card)", borderColor: "var(--color-border)" }}>
            {generatedAt && (
              <div className="text-xs mb-4 pb-4 border-b flex items-center justify-between" style={{ borderColor: "var(--color-border)", color: "var(--color-muted-foreground)" }}>
                <span>Generated: {new Date(generatedAt).toLocaleString()}</span>
                <span className="px-2 py-0.5 rounded text-xs" style={{ background: "oklch(0.65 0.18 145 / 0.1)", color: "oklch(0.75 0.15 145)", border: "1px solid oklch(0.65 0.18 145 / 0.3)" }}>CONFIDENTIAL</span>
              </div>
            )}
            <div
              className="prose prose-invert max-w-none text-sm leading-relaxed"
              style={{ color: "var(--color-foreground)" }}
              dangerouslySetInnerHTML={{ __html: html }}
            />
          </div>
        )}
      </div>
    </AppLayout>
  );
}
